
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.network :forwarded_port, guest: 80, host: 80
  config.vm.network :forwarded_port, guest: 443, host: 443

  config.vm.provision :shell, path: "setup-apache.sh"
  config.vm.provision :shell, path: "setup-python.sh"

end
